### ISSUE TITLE
can skywalking  support weblogic and ejb?

### ISSUE THREAD

**Issue by LifeFly** [OpenSkywalking/skywalking#531]
Please answer these questions before submitting your issue.

### What version of your OS?
llinux

### What version of your JRE?
1.8

### What company or project?
csair

### What did you do?

can skywalking  support weblogic and ejb?

**Comment by wu-sheng** [comment]
The Skywalking targets Cloud Native Java Stack. So Spring Cloud and Microservice architecture, or other language agents. So ejb is not our primary goals.

**But, A Big BUT**, my design of Java agent should work in other middlewares, such as weblogic. If you have any problem, we can discuss that. And since we have supported SpringMVC and Struts, even don't have the Weblogic plugin, you application is able to be instrumented as well.

EJB is truely not supported yet. But if you are interested, it would be hard to develop a new plugin, and we welcome your contribution. I assume you are a Chinese, you can check the zh-doc for plugin development: https://github.com/OpenSkywalking/skywalking/wiki/Plugin-Development-Guide

Hope this helps you.

**Comment by LifeFly** [comment]
ok  thank you. i will try to use Skywalking  with SpringMVC  plugin .

**Comment by wu-sheng** [comment]
@LifeFly FYI, most likely, you should pay attention about DB plugins. Some middeware connection pool mechanism didn't support our ways to do the intrumentation.
